### PR TITLE
gen_cs3_effects.py prototype

### PR DESCRIPTION
**Pull request by hwjsnc**
Prototype for generating the .ksy for effects from a CSV.

### CODE REVIEW

**Comment by nnguyen259** [comment]
One thing I'm curious about is whether or not we can setup something like a Github Action to automatically generate the file whenever a change is made to the csv for example

**Comment by ghost** [comment]
yes. it's very possible.

**Comment by hwjsnc** [comment]
There is one issue with this patch that I only just thought of: Since .csv is not standardized, different tools may encode it slightly differently, and editing even one line with tool A would change basically the entire file if the original was edited in tool B. For a clean version history, we should avoid this.

I can see three ways around this:
- Normalize the csv. For example, we could add a python script that reads a csv and then re-exports it, and run it before every commit. This might be stable enough across platforms and python versions to result in the same output no matter which tool was actually used for editing.
- Use a standardized format, though nothing particular comes to mind. Should have good tool support and be diffable.
- Use custom git diffs that ignores csv formatting.

**Comment by ghost** [comment]
csv is still the probably the best tool for the job unless there's a reaosnable json editor i don't know about.

If CSV then there should be a set of hard requirements:
 
 * all fields quoted (or at least all strings)
 * files must have unix line endings (LF)
 
The quoting rules are configurable in most tools. Others decide their default quoting based on whether the data has embedded control charcters or quotes

**Comment by hwjsnc** [comment]
JSON with whitespace would have the same issue as CSV, so if it's between these two, CSV is preferable afaic.

I added a script that normalizes CSVs to the requirements you mentioned (just run `normalize.py` from the `gen` subfolder before committing). I think that should be good enough as a start. We might want to add a CI hook to ensure only correctly formatted CSVs get merged as well.

**Comment by hwjsnc** [comment]
Had to fix the size of the data values (u4 instead of u2) and squashed and rebased the changes while I was at it.

**Pull request merged**
